feat: draft PR
SwellNetwork/subgraph pull request #1
Opened 2022-06-30 22:35 UTC by super1114

https://trello.com/c/j6lV9uxG/220-create-subgraph-to-query-referral

2022-07-03 02:13 UTC, leckylao requested changes
Why there's both package and yarn lock? And also yarn error? I reckon just use NPM for consistent

2022-07-03 03:42 UTC, super1114 commented
> consistent

removed yarn

2022-07-03 04:48 UTC, leckylao approved these changes

2022-07-04 12:55 UTC, daisai3 approved these changes
@super1114  LGTM!

2022-07-04 13:03 UTC, merged