feat: add stats entity including user counter
SwellNetwork/subgraph pull request #2
Opened 2022-07-09 02:54 UTC by KevinChristopher1014

2022-07-09 09:36 UTC, super1114 requested changes

2022-07-09 09:36 UTC, super1114 commented on src/swnft-upgrade.ts
> +    stats.userCounter = stats.userCounter.plus(BigInt.fromI32(1));
For increasing user count, same wallet can be considered one address right?
Should trigger the function for each user(different wallet) rather than for every event.

2022-07-09 09:36 UTC, super1114 commented on src/swnft-upgrade.ts
> +    stats.userCounter = stats.userCounter.plus(BigInt.fromI32(1));
How come `BigInt.fromI32`?

2022-07-10 13:05 UTC, leckylao commented on src/swnft-upgrade.ts
> +    let stats = Stats.load("1");
Why need to hardcode 1?

2022-07-10 13:08 UTC, KevinChristopher1014 commented on src/swnft-upgrade.ts
> +    let stats = Stats.load("1");
I stored stats data like this
{
   id: "1"
  userCounter: 1
}

2022-07-10 23:37 UTC, leckylao approved these changes

2022-07-11 00:27 UTC, super1114 approved these changes
LGTM

2022-07-14 03:50 UTC, merged